---
name: Submodule Bot

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch: ~

jobs:
  build:
    name: Submodule update
    runs-on: ubuntu-latest
    env:
      PARENT_REPOSITORY: "IU-Capstone-Project-2024/roomreco"
      CHECKOUT_BRANCH: "main"
      PR_AGAINST_BRANCH: "main"
      OWNER: "IU-Capstone-Project-2024"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: run action
        id: run_action
        uses: releasehub-com/github-action-create-pr-parent-submodule@v1
        with:
          github_token: ${{ secrets.TOKEN }}
          parent_repository: ${{ env.PARENT_REPOSITORY }}
          checkout_branch: ${{ env.CHECKOUT_BRANCH}}
          pr_against_branch: ${{ env.PR_AGAINST_BRANCH }}
          owner: ${{ env.OWNER }}
